// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBV6pTZdPyBvW8hYtwACkVokAXHSFM4TV4',
    appId: '1:425406739865:web:7cde54fbbea826d8f64f08',
    messagingSenderId: '425406739865',
    projectId: 'push-notification-5bf92',
    authDomain: 'push-notification-5bf92.firebaseapp.com',
    storageBucket: 'push-notification-5bf92.firebasestorage.app',
    measurementId: 'G-7P25LHBZ0P',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDzHNZtC7-9cqKD-bFjH_8n9TDjbHQyULQ',
    appId: '1:425406739865:android:1e8abaf367234594f64f08',
    messagingSenderId: '425406739865',
    projectId: 'push-notification-5bf92',
    storageBucket: 'push-notification-5bf92.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAqz-Ty3Y8nkbyek_pGC5rtsleu79QEDVU',
    appId: '1:425406739865:ios:41a7342afaeed01bf64f08',
    messagingSenderId: '425406739865',
    projectId: 'push-notification-5bf92',
    storageBucket: 'push-notification-5bf92.firebasestorage.app',
    iosBundleId: 'com.example.projectPushNoti',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAqz-Ty3Y8nkbyek_pGC5rtsleu79QEDVU',
    appId: '1:425406739865:ios:41a7342afaeed01bf64f08',
    messagingSenderId: '425406739865',
    projectId: 'push-notification-5bf92',
    storageBucket: 'push-notification-5bf92.firebasestorage.app',
    iosBundleId: 'com.example.projectPushNoti',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBV6pTZdPyBvW8hYtwACkVokAXHSFM4TV4',
    appId: '1:425406739865:web:69bc376fa8fd839ef64f08',
    messagingSenderId: '425406739865',
    projectId: 'push-notification-5bf92',
    authDomain: 'push-notification-5bf92.firebaseapp.com',
    storageBucket: 'push-notification-5bf92.firebasestorage.app',
    measurementId: 'G-Z95GWF4S6D',
  );
}
